### ISSUE TITLE
editing from ghci not possible due to non escapable characters

### ISSUE THREAD

**Issue by jonasatnewton** [theRealProHacker/tut-tool#17]
Run button works alright but when trying to edit from ghci with the `:e`-command the editor doesn't work with the parentheses contained in the path. Possible solution would be to set the working dir path of the launched terminal.

`Process.start("x-terminal-emulator", ["-e", "ghci", path],workingDirectory: p.dirname(file.path));`
setting it like this changes the path succesfully, only thing missing would be to change the `path` passed to ghci to the relative path in the working directory. (the latter is the reason I'm not just creating a PR)

**Comment by theRealProHacker** [comment]
Kannst du mir netterweise einfach mal ein Beispiel geben?
