### ISSUE TITLE
Suboptimale Darstellug auf 4:3

### ISSUE THREAD

**Issue by JBBgameich** [theRealProHacker/tut-tool#54]
Wenn das Fenster ca. im 4:3 Verhältis dargestellt wird, wird die Dateiliste nicht angezeigt, sondern nur das Kommentarfeld. Es gibt keinen (offensichtlichen) weg zur Dateiliste zu gelagen.

Meine beiden Monitore zuhause sind 4:3, deswegen betrifft mich das relativ stark.

**Comment by theRealProHacker** [comment]
Danke für dein Issue. Ich glaube, das hat nichts mit 4:3 zu tun, sondern einfach damit, dass ich vermeidbarerweise einen relativ großen Monitor vorausgesetzt habe. Mein eigentliches Ziel ist es, die Dateien bei der Hälfte des Screens auszublenden. Ich habe noch keine gute Lösung gefunden, dass auf allen Geräten gut zu lösen, aber ich arbeite daran. 
Als quick-fix mache ich einen Branch für kleine Geräte.

**Comment by theRealProHacker** [comment]
Der quick-fix ist in [diesem Branch](https://github.com/theRealProHacker/tut-tool/tree/small-screen-patch)
